name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # （デプロイを実施するトリガーとなるGitHubの操作を指定する）
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  # （Actionsのジョブを手動でも実行できるようにする）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # （リポジトリの内容をActions上の仮想環境にチェックアウト）
      - uses: actions/checkout@v3
      
      # Install SSH Key
      # （有志の方が作成したActionsを用い、リポジトリのSecretsとして登録してある秘密鍵を仮想環境上に持ってくる）
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with: # shimataro/ssh-key-actionに渡すパラメーター
          key: ${{ secrets.SSH_KEY }} # 必須
          known_hosts: ${{ secrets.KNOWN_HOSTS }} # 必須
          config: | 
            Host target
              HostName 18.176.3.96
              User ubuntu
              IdentityFile ~/.ssh/id_rsa

      - name: Deploy to Demo-Server
        run: scp -r README.md ubuntu@target:/home/ubuntu/scp_test
     #   run: scp -r nuxtjs/src ubuntu@target:/home/ubuntu/monodance/nuxtjs

      - name: Deploy to Nuxtjs Container from Demo-Server
        run: ssh target sudo docker cp monodance/nuxtjs/src monodance_nuxtjs_1:/home/node

      - name: Execute "npm run build"
        run: ssh target sudo docker exec monodance_nuxtjs_1 /bin/bash /home/node/src/nuxt_build.sh 

      - name: Killing old Process and Execute "npm run start"
        run: ssh target sudo docker exec -d monodance_nuxtjs_1 /bin/bash /home/node/src/nuxt_restart.sh 
